import { PayoutPartnerProfile } from "./payoutTypes";

export const payoutPartnerDirectory: PayoutPartnerProfile[] = [
  {
    id: "NIUM_SANDBOX",
    name: "Nium Sandbox",
    supportedCountries: [
      "Malaysia",
      "UAE",
      "Saudi Arabia",
      "Qatar",
      "Kuwait",
      "Bahrain",
      "Oman",
      "Singapore",
    ],
    supportedCurrencies: ["MYR", "AED", "SAR", "QAR", "KWD", "BHD", "OMR", "SGD"],
    supportedPayoutMethods: ["BANK"],
    supportedBanks: [
      "Maybank",
      "CIMB",
      "Emirates NBD",
      "ADCB",
      "Al Rajhi Bank",
      "SNB",
      "QNB",
      "NBK",
      "NBB",
      "Bank Muscat",
      "DBS",
      "OCBC",
      "UOB",
    ],
    priority: 1,
    estimatedMinutes: 2,
    reliabilityScore: 92,
    feeScore: 85,
    sandboxReady: false,
    requiresCredentials: true,
  },
  {
    id: "THUNES_SANDBOX",
    name: "Thunes Sandbox",
    supportedCountries: [
      "Malaysia",
      "Philippines",
      "UAE",
      "Saudi Arabia",
      "Qatar",
      "Kuwait",
      "Bahrain",
      "Oman",
      "Singapore",
      "Thailand",
      "Indonesia",
      "Vietnam",
    ],
    supportedCurrencies: [
      "MYR",
      "PHP",
      "AED",
      "SAR",
      "QAR",
      "KWD",
      "BHD",
      "OMR",
      "SGD",
      "THB",
      "IDR",
      "VND",
    ],
    supportedPayoutMethods: ["BANK", "MOBILE_WALLET"],
    supportedBanks: [
      "Maybank",
      "BDO",
      "GCash",
      "Emirates NBD",
      "Al Rajhi Bank",
      "QNB",
      "NBK",
      "NBB",
      "Bank Muscat",
      "DBS",
      "Bangkok Bank",
      "BCA",
      "Vietcombank",
    ],
    priority: 2,
    estimatedMinutes: 3,
    reliabilityScore: 90,
    feeScore: 80,
    sandboxReady: false,
    requiresCredentials: true,
  },
  {
    id: "NEXTPAY_SANDBOX",
    name: "NextPay Sandbox",
    supportedCountries: ["Philippines", "Thailand", "Indonesia", "Vietnam"],
    supportedCurrencies: ["PHP", "THB", "IDR", "VND"],
    supportedPayoutMethods: ["BANK"],
    supportedBanks: ["BDO", "BPI", "UnionBank", "Bangkok Bank", "BCA", "Vietcombank"],
    priority: 1,
    estimatedMinutes: 2,
    reliabilityScore: 88,
    feeScore: 90,
    sandboxReady: false,
    requiresCredentials: true,
  },
  {
    id: "TRANGLO_SANDBOX",
    name: "Tranglo Sandbox",
    supportedCountries: ["Malaysia", "Philippines", "Singapore", "Thailand", "Indonesia"],
    supportedCurrencies: ["MYR", "PHP", "SGD", "THB", "IDR"],
    supportedPayoutMethods: ["BANK"],
    supportedBanks: ["Maybank", "BDO", "DBS", "Bangkok Bank", "BCA"],
    priority: 3,
    estimatedMinutes: 4,
    reliabilityScore: 85,
    feeScore: 78,
    sandboxReady: false,
    requiresCredentials: true,
  },
];
