import { PayoutPartnerProfile } from "./payoutTypes";

export const payoutPartnerDirectory: PayoutPartnerProfile[] = [
  {
    id: "NIUM_SANDBOX",
    name: "Nium Sandbox",
    supportedCountries: ["Malaysia", "UAE"],
    supportedCurrencies: ["MYR", "AED"],
    supportedPayoutMethods: ["BANK"],
    supportedBanks: ["Maybank", "CIMB", "Emirates NBD", "ADCB"],
    priority: 1,
    estimatedMinutes: 2,
    reliabilityScore: 92,
    feeScore: 85,
    sandboxReady: false,
    requiresCredentials: true,
  },
  {
    id: "THUNES_SANDBOX",
    name: "Thunes Sandbox",
    supportedCountries: ["Malaysia", "Philippines", "UAE"],
    supportedCurrencies: ["MYR", "PHP", "AED"],
    supportedPayoutMethods: ["BANK", "MOBILE_WALLET"],
    supportedBanks: ["Maybank", "BDO", "GCash", "Emirates NBD"],
    priority: 2,
    estimatedMinutes: 3,
    reliabilityScore: 90,
    feeScore: 80,
    sandboxReady: false,
    requiresCredentials: true,
  },
  {
    id: "NEXTPAY_SANDBOX",
    name: "NextPay Sandbox",
    supportedCountries: ["Philippines"],
    supportedCurrencies: ["PHP"],
    supportedPayoutMethods: ["BANK"],
    supportedBanks: ["BDO", "BPI", "UnionBank"],
    priority: 1,
    estimatedMinutes: 2,
    reliabilityScore: 88,
    feeScore: 90,
    sandboxReady: false,
    requiresCredentials: true,
  },
  {
    id: "TRANGLO_SANDBOX",
    name: "Tranglo Sandbox",
    supportedCountries: ["Malaysia", "Philippines"],
    supportedCurrencies: ["MYR", "PHP"],
    supportedPayoutMethods: ["BANK"],
    supportedBanks: ["Maybank", "BDO"],
    priority: 3,
    estimatedMinutes: 4,
    reliabilityScore: 85,
    feeScore: 78,
    sandboxReady: false,
    requiresCredentials: true,
  },
];
