import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, TextInput, View } from "react-native";

import { RoutePlanComparison } from "../src/components/routes/RoutePlanComparison";
import { AppButton } from "../src/components/ui/AppButton";
import { AppCard } from "../src/components/ui/AppCard";
import { AppText } from "../src/components/ui/AppText";
import { Screen } from "../src/components/ui/Screen";
import { corridors } from "../src/data/corridors";
import { useCanonicalRouteQuotes } from "../src/hooks/useCanonicalRouteQuotes";

export default function QuoteScreen() {
  const [amount, setAmount] = useState("100");
  const [selectedCountry, setSelectedCountry] = useState("Philippines");
  const selectedCorridor = useMemo(
    () => corridors.find((corridor) => corridor.country === selectedCountry),
    [selectedCountry],
  );
  const numericAmount = Number(amount);
  const routeResult = useCanonicalRouteQuotes({
    amount: Number.isFinite(numericAmount) ? numericAmount : 0,
    destinationCurrency: selectedCorridor?.currency,
    destinationCountry: selectedCorridor?.country,
    payoutMethod: "BANK",
    fundingMethod: "OPEN_BANKING",
  });

  return (
    <Screen>
      <ScrollView showsVerticalScrollIndicator={false}>
        <View style={{ gap: 18, paddingBottom: 40 }}>
          <View style={{ gap: 6 }}>
            <AppText variant="title">Route Intelligence</AppText>
            <AppText variant="caption">
              Evidence-backed candidates generated by the canonical Route Plan engine.
            </AppText>
          </View>

          <AppCard>
            <View style={{ gap: 12 }}>
              <AppText variant="subheading">Check a route</AppText>
              <TextInput
                value={amount}
                onChangeText={setAmount}
                keyboardType="decimal-pad"
                placeholder="Enter GBP amount"
                style={{ borderWidth: 1, borderColor: "#D6D6D6", borderRadius: 14, padding: 14, fontSize: 18 }}
              />
              <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>
                {corridors.map((corridor) => {
                  const selected = corridor.country === selectedCountry;
                  return (
                    <Pressable
                      key={corridor.country}
                      onPress={() => setSelectedCountry(corridor.country)}
                      style={{
                        paddingVertical: 10,
                        paddingHorizontal: 14,
                        borderRadius: 999,
                        borderWidth: 1,
                        borderColor: selected ? "#111827" : "#D6D6D6",
                        backgroundColor: selected ? "#111827" : "#FFFFFF",
                      }}
                    >
                      <AppText style={{ color: selected ? "#FFFFFF" : "#111827", fontWeight: "700" }}>
                        {corridor.country}
                      </AppText>
                    </Pressable>
                  );
                })}
              </View>
              <AppText variant="caption">GBP to {selectedCorridor?.currency ?? "destination"}</AppText>
            </View>
          </AppCard>

          {routeResult.loading ? <AppCard><AppText variant="body">Loading current evidence...</AppText></AppCard> : null}
          {routeResult.error ? <AppCard><AppText variant="body">{routeResult.error}</AppText></AppCard> : null}

          {routeResult.routes.map((route) => {
            const plan = route.routePlan!;
            return (
              <AppCard key={route.id}>
                <View style={{ gap: 12 }}>
                  <View style={{ flexDirection: "row", justifyContent: "space-between", gap: 12 }}>
                    <View style={{ flex: 1 }}>
                      <AppText variant="subheading">{route.provider}</AppText>
                      <AppText variant="caption">
                        {plan.eligible ? `Rank ${plan.rank} evidence candidate` : "Unavailable for approval"}
                      </AppText>
                    </View>
                    <AppText variant="subheading">{plan.score.value == null ? "NO SCORE" : `${plan.score.value}/100`}</AppText>
                  </View>
                  <RoutePlanComparison plan={plan} />
                  {!plan.eligible ? plan.eligibilityReasons.map((reason) => (
                    <AppText key={reason} variant="caption">• {reason}</AppText>
                  )) : null}
                </View>
              </AppCard>
            );
          })}

          <AppButton
            title="Continue to payment setup"
            onPress={() => router.push({ pathname: "/send", params: { amount, country: selectedCountry } })}
          />
          <AppButton title="Back home" variant="secondary" onPress={() => router.push("/")} />
        </View>
      </ScrollView>
    </Screen>
  );
}
